### PR TITLE
Revert "Coloring multiple regions of interest"

### PR DESCRIPTION
**Pull request by sahirbhatnagar**
Reverts sahirbhatnagar/manhattanly#2

There is an error when trying to build the vignette. See https://travis-ci.org/sahirbhatnagar/manhattanly/builds/153970939 for details. I will merge once its fixed. Thanks

### CODE REVIEW

**Comment by nemami** [comment]
Not sure where the bug is -- no issues on my end:

```
> library(devtools)
> install_github("nemami/manhattanly")
Downloading GitHub repo nemami/manhattanly@master
from URL https://api.github.com/repos/nemami/manhattanly/zipball/master
Installing manhattanly
'/usr/local/Cellar/r/3.2.3/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
 '/private/var/folders/hr/kf_slysx11v57116n2740bsw0000gn/T/Rtmpfj9Qqa/devtools254533f80406/nemami-manhattanly-7d5eed9'  \
  --library='/usr/local/lib/R/3.2/site-library' --install-tests 
* installing *source* package ‘manhattanly’ ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (manhattanly)
```

**Comment by sahirbhatnagar** [comment]
Can you try building the vignette locally using `devtools::build_vignettes()`

**Comment by nemami** [comment]
Apologies for the delay. Indeed, building locally throws a warning and prompts the installation of 2 packages "Pandoc" and "pandoc-citeproc," neither of which appears to be available?

```
> install.packages("Pandoc")
Installing package into ‘/usr/local/lib/R/3.2/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘Pandoc’ is not available (for R version 3.2.3) 
> install.packages("pandoc-citeproc")
Installing package into ‘/usr/local/lib/R/3.2/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘pandoc-citeproc’ is not available (for R version 3.2.3) 
```

However, I'm not sure if this is a result of the code in my pull request -- I think I'm seeing the same warning in the current master branch.

```
bash-3.2$ git clone https://github.com/sahirbhatnagar/manhattanly.git
Cloning into 'manhattanly'...
remote: Counting objects: 381, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 381 (delta 5), reused 0 (delta 0), pack-reused 361
Receiving objects: 100% (381/381), 10.46 MiB | 6.27 MiB/s, done.
Resolving deltas: 100% (189/189), done.
Checking connectivity... done.
bash-3.2$ R

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(devtools)
> devtools::build_vignettes("./manhattanly")
Building manhattanly vignettes
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
Error: processing vignette 'manhattanly.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because manhattanly.Rmd appears to be an R Markdown v2 document.
```

**Comment by sahirbhatnagar** [comment]
I have located the bug. When I compile your vignette I get the following error 

```
Error in manhattanly(subset(HapMap, CHR %in% 4:7), snp = "SNP", gene = "GENE") : 
  argument 2 matches multiple formal arguments
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> manhattanly Execution halted
```

The problem is that the function arguments you have added `snpSets` and `snpSetColors` are partial matches with the original `snp` argument. So in the error above, the function does not know which function argument `"SNP"` should be assigned to. See https://cran.r-project.org/doc/manuals/R-lang.html#Argument-matching for further details on partial matching of function arguments.

**Comment by nemami** [comment]
Very interesting, nice find! I wonder why some of the other arguments wouldn't have this issue as well (e.g. `genomewideline` vs. `genomewideline_color` & `genomewideline_width`). Perhaps the addition of delimiters mitigates this issue? On [stackoverflow](http://stackoverflow.com/questions/14153904/partial-matching-of-function-argument) it's suggested that R uses the `pmatch` function to evaluate argument matching internally. It's unclear why it would evaluate those cases differently (see below) -- perhaps the addition of the underscore delimiters? If that is a fix I would gladly resubmit the pull with those changes and whatever others are suitable or necessary. Or maybe what's happening is that the `genomewideline` argument isn't invoked in the vignettes, whereas the `SNP` argument is -- so setting `genomewideline` to a non-default input would perhaps also cause the build to fail?

```
# Each case returns 'NA' due to multiple matches
> pmatch("snp",c("snpSets","snpSetColors"))
[1] NA
> pmatch("genomewideline",c("genomewideline_color","genomewideline_width"))
[1] NA
> pmatch("suggestiveline",c("suggestiveline_color","suggestiveline_width"))
[1] NA
```

**Comment by sahirbhatnagar** [comment]
Good catch. I don't fully understand the behavior of `pmatch`. Nevertheless, I think the addition of the underscore should fix the issue. Please resubmit the pull and hopefully it works.

**Pull request merged**
